# theme.toml for the YNC Hugo theme

name = "Demo Ghagvid Theme"
license = "CC BY 3.0"
licenselink = ""
description = ""
homepage = ""
tags = ["blog",'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'multilingual',
"portfolio", "projects", "responsive"]
features = ["blog", "personal", "responsive", "seo-friendly"]
min_version = 0.1

[author]
  name = "oneclicktheme"
  homepage = "https://www.oneclicktheme.com/"

[original]
  name = ""
  homepage = "/"
  repo = ""
